const companies = [
  {
    id: 'tcs', name: 'TCS', type: 'service', logo: '🏢',
    difficulty: 'Easy', dsaLevel: 'Basics', aptitude: true,
    rounds: ['Online Aptitude', 'Technical Interview', 'HR'],
    skills: ['C/C++/Java Basics', 'DBMS', 'OS', 'Aptitude'],
    timeline: '3-4 weeks', projectExpectation: 'Low',
    tips: 'Focus heavily on aptitude and basic CS concepts. DSA is minimal.',
  },
  {
    id: 'infosys', name: 'Infosys', type: 'service', logo: '🔷',
    difficulty: 'Easy', dsaLevel: 'Basics', aptitude: true,
    rounds: ['Online Test (Aptitude + Coding)', 'Technical Interview', 'HR'],
    skills: ['Basic Programming', 'DBMS', 'Communication'],
    timeline: '3-4 weeks', projectExpectation: 'Low',
    tips: 'Communication skills are very important. Write clean code.',
  },
  {
    id: 'wipro', name: 'Wipro', type: 'service', logo: '🟣',
    difficulty: 'Easy', dsaLevel: 'Basics', aptitude: true,
    rounds: ['AMCAT Test', 'Technical Interview', 'HR'],
    skills: ['Aptitude', 'Basic Programming', 'Verbal'],
    timeline: '2-3 weeks', projectExpectation: 'Low',
    tips: 'AMCAT score matters a lot. Practice verbal and quant heavily.',
  },
  {
    id: 'accenture', name: 'Accenture', type: 'service', logo: '🔺',
    difficulty: 'Easy-Medium', dsaLevel: 'Easy', aptitude: true,
    rounds: ['Cognitive + Technical Assessment', 'Technical Interview', 'HR'],
    skills: ['Aptitude', 'Basic DSA', 'Communication'],
    timeline: '3-4 weeks', projectExpectation: 'Low-Medium',
    tips: 'Cognitive assessment is the toughest part. Practice logical reasoning.',
  },
  {
    id: 'amazon', name: 'Amazon', type: 'product', logo: '📦',
    difficulty: 'Hard', dsaLevel: 'Medium-Hard', aptitude: false,
    rounds: ['OA (2 coding problems)', 'Technical Round 1', 'Technical Round 2', 'Bar Raiser', 'HR'],
    skills: ['Strong DSA', 'System Design Basics', 'Leadership Principles'],
    timeline: '2-3 months', projectExpectation: 'High',
    tips: 'Know all 16 Leadership Principles deeply. OA has tricky edge cases.',
  },
  {
    id: 'microsoft', name: 'Microsoft', type: 'product', logo: '🪟',
    difficulty: 'Hard', dsaLevel: 'Medium-Hard', aptitude: false,
    rounds: ['OA', 'Technical Round 1', 'Technical Round 2', 'Technical Round 3', 'HR'],
    skills: ['Strong DSA', 'OOP', 'System Design', 'CS Fundamentals'],
    timeline: '2-3 months', projectExpectation: 'High',
    tips: 'CS fundamentals are asked more than at other companies. Know OS, CN deeply.',
  },
  {
    id: 'google', name: 'Google', type: 'product', logo: '🔍',
    difficulty: 'Very Hard', dsaLevel: 'Hard', aptitude: false,
    rounds: ['OA', '4-5 Technical Rounds', 'Team Match', 'Hiring Committee'],
    skills: ['Advanced DSA', 'System Design', 'Algorithms', 'CS Theory'],
    timeline: '4-6 months', projectExpectation: 'Very High',
    tips: 'Practice hard LeetCode. Graphs, DP, and System Design are critical.',
  },
  {
    id: 'flipkart', name: 'Flipkart', type: 'product', logo: '🛒',
    difficulty: 'Hard', dsaLevel: 'Medium-Hard', aptitude: false,
    rounds: ['OA', 'Technical Round 1', 'Technical Round 2', 'Hiring Manager'],
    skills: ['Strong DSA', 'System Design', 'Backend skills'],
    timeline: '2-3 months', projectExpectation: 'High',
    tips: 'System design is asked even at fresher level. Prepare LLD basics.',
  },
  {
    id: 'startups', name: 'Startups', type: 'startup', logo: '🚀',
    difficulty: 'Varies', dsaLevel: 'Easy-Medium', aptitude: false,
    rounds: ['Assignment/OA', 'Technical Interview', 'Culture Fit'],
    skills: ['Full Stack', 'Projects', 'Problem Solving', 'Ship fast mentality'],
    timeline: '2-4 weeks', projectExpectation: 'Very High',
    tips: 'Projects matter more than DSA here. Show you can build real things.',
  },
];

export default companies;
