const stages = [
  {
    id: 'stage-1',
    stageNumber: 1,
    title: 'Mindset & Placement Setup',
    description: 'Understand how campus placements work, build the right mindset, and set up your tools.',
    difficulty: 'Beginner',
    estimatedWeeks: 1,
    icon: '🧠',
    color: '#40e0d0',
    topics: [
      { id: 't1-1', title: 'How Campus Placements Work', type: 'concept', duration: '30 min' },
      { id: 't1-2', title: 'On-Campus vs Off-Campus', type: 'concept', duration: '20 min' },
      { id: 't1-3', title: 'How Recruiters Shortlist Candidates', type: 'concept', duration: '20 min' },
      { id: 't1-4', title: 'Tier-3 College Strategy', type: 'concept', duration: '30 min' },
      { id: 't1-5', title: 'Common Student Mistakes', type: 'concept', duration: '20 min' },
      { id: 't1-6', title: 'How Much DSA Is Enough', type: 'concept', duration: '20 min' },
      { id: 't1-7', title: 'Tools Setup: VS Code, Git, GitHub, Terminal', type: 'setup', duration: '2 hrs' },
    ],
    tasks: [
      'Create a GitHub profile and push your first repo',
      'Install VS Code with extensions: Prettier, GitLens, ES7 Snippets',
      'Write down your target companies (3 dream, 3 realistic, 3 backup)',
      'Set a 6-month placement timeline',
    ],
    resources: [
      { title: 'TakeUForward Placement Guide', url: 'https://takeuforward.org', type: 'website' },
      { title: 'Git & GitHub Crash Course', url: 'https://www.youtube.com/watch?v=RGOj5yH7evk', type: 'video' },
    ],
    whatToIgnore: [
      'Don\'t panic about which language to choose — pick one and stick with it',
      'Don\'t spend weeks setting up the "perfect" environment',
    ],
  },
  {
    id: 'stage-2',
    stageNumber: 2,
    title: 'Programming Fundamentals',
    description: 'Build a strong foundation in your chosen language before moving to DSA.',
    difficulty: 'Beginner',
    estimatedWeeks: 3,
    icon: '📝',
    color: '#a78bfa',
    topics: [
      { id: 't2-1', title: 'Choose Your Language (C++/Java/Python/JS)', type: 'concept', duration: '1 day' },
      { id: 't2-2', title: 'Variables & Data Types', type: 'concept', duration: '2 hrs' },
      { id: 't2-3', title: 'Operators', type: 'concept', duration: '1 hr' },
      { id: 't2-4', title: 'Conditions & Loops', type: 'concept', duration: '3 hrs' },
      { id: 't2-5', title: 'Functions', type: 'concept', duration: '3 hrs' },
      { id: 't2-6', title: 'Arrays', type: 'concept', duration: '4 hrs' },
      { id: 't2-7', title: 'Strings', type: 'concept', duration: '3 hrs' },
      { id: 't2-8', title: 'Recursion Basics', type: 'concept', duration: '5 hrs' },
      { id: 't2-9', title: 'OOP Concepts', type: 'concept', duration: '6 hrs' },
      { id: 't2-10', title: 'Exception Handling', type: 'concept', duration: '2 hrs' },
      { id: 't2-11', title: 'File Handling', type: 'concept', duration: '2 hrs' },
    ],
    tasks: [
      'Solve 20 basic problems on HackerRank',
      'Implement a simple calculator using functions',
      'Write a program using all OOP concepts',
    ],
    resources: [
      { title: 'CS50 Introduction to Programming', url: 'https://cs50.harvard.edu', type: 'course' },
      { title: 'Apna College C++ Playlist', url: 'https://www.youtube.com/@ApnaCollegeOfficial', type: 'video' },
    ],
    whatToIgnore: [
      'Don\'t learn multiple languages at once',
      'Don\'t skip recursion — it\'s the base of all DSA',
    ],
  },
  {
    id: 'stage-3',
    stageNumber: 3,
    title: 'Data Structures & Algorithms',
    description: 'The heart of placement prep. Master DSA patterns to crack any coding round.',
    difficulty: 'Intermediate',
    estimatedWeeks: 12,
    icon: '🧩',
    color: '#f472b6',
    topics: [
      { id: 't3-1', title: 'Time & Space Complexity', type: 'dsa', duration: '3 hrs' },
      { id: 't3-2', title: 'Arrays', type: 'dsa', duration: '1 week' },
      { id: 't3-3', title: 'Strings', type: 'dsa', duration: '3 days' },
      { id: 't3-4', title: 'Linked List', type: 'dsa', duration: '1 week' },
      { id: 't3-5', title: 'Stack', type: 'dsa', duration: '3 days' },
      { id: 't3-6', title: 'Queue', type: 'dsa', duration: '2 days' },
      { id: 't3-7', title: 'Hashing', type: 'dsa', duration: '3 days' },
      { id: 't3-8', title: 'Recursion & Backtracking', type: 'dsa', duration: '1 week' },
      { id: 't3-9', title: 'Binary Search', type: 'dsa', duration: '5 days' },
      { id: 't3-10', title: 'Sliding Window & Two Pointers', type: 'dsa', duration: '4 days' },
      { id: 't3-11', title: 'Trees & BST', type: 'dsa', duration: '2 weeks' },
      { id: 't3-12', title: 'Heap / Priority Queue', type: 'dsa', duration: '4 days' },
      { id: 't3-13', title: 'Graphs (BFS/DFS/Topo)', type: 'dsa', duration: '2 weeks' },
      { id: 't3-14', title: 'Greedy Algorithms', type: 'dsa', duration: '5 days' },
      { id: 't3-15', title: 'Dynamic Programming', type: 'dsa', duration: '3 weeks' },
      { id: 't3-16', title: 'Trie', type: 'dsa', duration: '3 days' },
      { id: 't3-17', title: 'Segment Tree', type: 'dsa', duration: '3 days' },
    ],
    tasks: [
      'Complete Striver\'s A2Z DSA Sheet (450 problems)',
      'Solve 5 problems daily — minimum 2 medium',
      'Revise every topic after completion with 3 hard problems',
      'Track solved problems on a spreadsheet',
    ],
    resources: [
      { title: 'Striver\'s A2Z DSA Sheet', url: 'https://takeuforward.org/strivers-a2z-dsa-course', type: 'course' },
      { title: 'NeetCode.io', url: 'https://neetcode.io', type: 'website' },
      { title: 'LeetCode', url: 'https://leetcode.com', type: 'practice' },
    ],
    whatToIgnore: [
      'Don\'t skip easy problems — patterns matter',
      'Don\'t spend more than 30 min stuck — look at hint then solve yourself',
      'Don\'t jump to DP without completing Arrays, Trees, Graphs',
    ],
  },
  {
    id: 'stage-4',
    stageNumber: 4,
    title: 'Core CS Subjects',
    description: 'DBMS, OS, CN, and OOP — asked in every technical interview.',
    difficulty: 'Intermediate',
    estimatedWeeks: 4,
    icon: '🎓',
    color: '#fb923c',
    topics: [
      { id: 't4-1', title: 'DBMS: ER Model, SQL, Joins, Normalization', type: 'cs', duration: '1 week' },
      { id: 't4-2', title: 'DBMS: Transactions & Indexing', type: 'cs', duration: '3 days' },
      { id: 't4-3', title: 'OS: Process, Threads, Scheduling', type: 'cs', duration: '1 week' },
      { id: 't4-4', title: 'OS: Deadlock, Memory Management, Paging', type: 'cs', duration: '4 days' },
      { id: 't4-5', title: 'CN: OSI Model, TCP/IP, HTTP/HTTPS', type: 'cs', duration: '4 days' },
      { id: 't4-6', title: 'CN: DNS, Routing', type: 'cs', duration: '2 days' },
      { id: 't4-7', title: 'OOP: Classes, Inheritance, Polymorphism', type: 'cs', duration: '3 days' },
      { id: 't4-8', title: 'OOP: Encapsulation, Abstraction, SOLID', type: 'cs', duration: '3 days' },
    ],
    tasks: [
      'Write SQL queries for 30 classic problems',
      'Explain OS scheduling algorithms with examples',
      'Draw the OSI model from memory',
      'Implement all OOP pillars in code',
    ],
    resources: [
      { title: 'InterviewBit CS Fundamentals', url: 'https://www.interviewbit.com/courses/programming', type: 'website' },
      { title: 'Gate Smashers Playlists', url: 'https://www.youtube.com/@GateSmashers', type: 'video' },
    ],
    whatToIgnore: [
      'Don\'t memorize — understand concepts and implement them',
    ],
  },
  {
    id: 'stage-5',
    stageNumber: 5,
    title: 'Development Skills',
    description: 'Learn the tools and tech stack companies actually use in production.',
    difficulty: 'Intermediate',
    estimatedWeeks: 6,
    icon: '🛠️',
    color: '#34d399',
    topics: [
      { id: 't5-1', title: 'Git & GitHub (Advanced)', type: 'dev', duration: '2 days' },
      { id: 't5-2', title: 'HTML & CSS', type: 'dev', duration: '1 week' },
      { id: 't5-3', title: 'JavaScript (ES6+)', type: 'dev', duration: '2 weeks' },
      { id: 't5-4', title: 'React.js', type: 'dev', duration: '2 weeks' },
      { id: 't5-5', title: 'Node.js & Express.js', type: 'dev', duration: '1 week' },
      { id: 't5-6', title: 'REST APIs & Authentication (JWT)', type: 'dev', duration: '4 days' },
      { id: 't5-7', title: 'MongoDB & PostgreSQL', type: 'dev', duration: '1 week' },
      { id: 't5-8', title: 'Deployment (Vercel, Render)', type: 'dev', duration: '2 days' },
      { id: 't5-9', title: 'Docker Basics', type: 'dev', duration: '3 days' },
      { id: 't5-10', title: 'System Design Basics', type: 'dev', duration: '1 week' },
    ],
    tasks: [
      'Deploy a full-stack app to Vercel + Render',
      'Build and document a REST API with Postman',
      'Contribute to one open-source repo',
    ],
    resources: [
      { title: 'The Odin Project', url: 'https://www.theodinproject.com', type: 'course' },
      { title: 'Roadmap.sh', url: 'https://roadmap.sh', type: 'website' },
    ],
    whatToIgnore: [
      'Don\'t try to learn every framework — pick one frontend and one backend',
      'Don\'t build 10 small projects — build 2-3 solid ones',
    ],
  },
  {
    id: 'stage-6',
    stageNumber: 6,
    title: 'Projects',
    description: 'Build real-world projects that stand out on your resume and in interviews.',
    difficulty: 'Intermediate',
    estimatedWeeks: 6,
    icon: '🚀',
    color: '#60a5fa',
    topics: [
      { id: 't6-1', title: 'Beginner: Todo App', type: 'project', duration: '2 days', category: 'Beginner' },
      { id: 't6-2', title: 'Beginner: Weather App', type: 'project', duration: '2 days', category: 'Beginner' },
      { id: 't6-3', title: 'Intermediate: Blog App', type: 'project', duration: '1 week', category: 'Intermediate' },
      { id: 't6-4', title: 'Intermediate: Chat App (Socket.io)', type: 'project', duration: '1 week', category: 'Intermediate' },
      { id: 't6-5', title: 'Advanced: Job Portal', type: 'project', duration: '2 weeks', category: 'Advanced' },
      { id: 't6-6', title: 'Advanced: AI Resume Analyzer', type: 'project', duration: '2 weeks', category: 'Advanced' },
      { id: 't6-7', title: 'Advanced: Placement Tracking Platform', type: 'project', duration: '3 weeks', category: 'Advanced' },
    ],
    tasks: [
      'Deploy every project — a local project doesn\'t count',
      'Write a good README for every project',
      'Prepare 5 interview questions from each project',
      'Record a 2-min demo video of your best project',
    ],
    resources: [
      { title: 'GitHub Project Ideas', url: 'https://github.com/practical-tutorials/project-based-learning', type: 'website' },
    ],
    whatToIgnore: [
      'Don\'t build projects without deploying them',
      'Don\'t add a project to resume if you can\'t explain every line of code',
    ],
  },
  {
    id: 'stage-7',
    stageNumber: 7,
    title: 'Aptitude & Communication',
    description: 'Clear aptitude rounds and communicate confidently in HR and GD rounds.',
    difficulty: 'Beginner',
    estimatedWeeks: 3,
    icon: '🗣️',
    color: '#fbbf24',
    topics: [
      { id: 't7-1', title: 'Quantitative Aptitude', type: 'aptitude', duration: '1 week' },
      { id: 't7-2', title: 'Logical Reasoning', type: 'aptitude', duration: '4 days' },
      { id: 't7-3', title: 'Puzzles', type: 'aptitude', duration: '3 days' },
      { id: 't7-4', title: 'English Communication', type: 'communication', duration: '4 days' },
      { id: 't7-5', title: 'Self Introduction (Tell Me About Yourself)', type: 'communication', duration: '2 days' },
      { id: 't7-6', title: 'Group Discussion Techniques', type: 'communication', duration: '2 days' },
      { id: 't7-7', title: 'HR Questions Masterlist', type: 'communication', duration: '3 days' },
    ],
    tasks: [
      'Practice 20 aptitude questions daily on IndiaBix',
      'Record yourself giving a self-introduction — review and improve',
      'Participate in 2 mock GD sessions',
    ],
    resources: [
      { title: 'IndiaBix Aptitude', url: 'https://www.indiabix.com', type: 'practice' },
      { title: 'Speak English Fluently', url: 'https://www.youtube.com/@tseries', type: 'video' },
    ],
    whatToIgnore: [
      'Don\'t ignore aptitude — many companies filter 80% here',
      'Don\'t read HR answers from a script — be genuine',
    ],
  },
  {
    id: 'stage-8',
    stageNumber: 8,
    title: 'Interview Preparation',
    description: 'Strategy and practice for coding rounds, technical interviews, and HR.',
    difficulty: 'Advanced',
    estimatedWeeks: 4,
    icon: '🎯',
    color: '#f87171',
    topics: [
      { id: 't8-1', title: 'Coding Interview Strategy', type: 'interview', duration: '2 days' },
      { id: 't8-2', title: 'Mock Coding Rounds (Timed)', type: 'interview', duration: '1 week' },
      { id: 't8-3', title: 'Technical Interview Simulation', type: 'interview', duration: '1 week' },
      { id: 't8-4', title: 'Behavioral Interview — STAR Method', type: 'interview', duration: '3 days' },
      { id: 't8-5', title: 'System Design Basics for Interviews', type: 'interview', duration: '5 days' },
      { id: 't8-6', title: 'Common Interview Mistakes', type: 'interview', duration: '1 day' },
    ],
    tasks: [
      'Give 3 mock interviews on Pramp or Interviewing.io',
      'Practice explaining your approach before coding',
      'Prepare STAR answers for 10 behavioral questions',
    ],
    resources: [
      { title: 'Pramp Mock Interviews', url: 'https://www.pramp.com', type: 'practice' },
      { title: 'Interviewing.io', url: 'https://interviewing.io', type: 'practice' },
      { title: 'System Design Primer', url: 'https://github.com/donnemartin/system-design-primer', type: 'website' },
    ],
    whatToIgnore: [
      'Don\'t memorize solutions — understand the pattern',
      'Don\'t jump to code without explaining your approach',
    ],
  },
  {
    id: 'stage-9',
    stageNumber: 9,
    title: 'Resume & LinkedIn',
    description: 'Create a resume that gets shortlisted and a LinkedIn that attracts recruiters.',
    difficulty: 'Beginner',
    estimatedWeeks: 1,
    icon: '📄',
    color: '#c084fc',
    topics: [
      { id: 't9-1', title: 'Resume Structure & ATS Optimization', type: 'resume', duration: '1 day' },
      { id: 't9-2', title: 'Writing Strong Project Descriptions', type: 'resume', duration: '1 day' },
      { id: 't9-3', title: 'LinkedIn Profile Setup', type: 'linkedin', duration: '1 day' },
      { id: 't9-4', title: 'LinkedIn Headline & About Section', type: 'linkedin', duration: '3 hrs' },
      { id: 't9-5', title: 'Cold Messaging & Referral Templates', type: 'linkedin', duration: '3 hrs' },
    ],
    tasks: [
      'Get your resume reviewed on r/cscareerquestions or by a mentor',
      'Connect with 20 engineers at your target companies',
      'Send 5 cold messages using the referral template',
    ],
    resources: [
      { title: 'Jake\'s Resume Template', url: 'https://www.overleaf.com/latex/templates/jakes-resume', type: 'template' },
      { title: 'Resume Worded (ATS Check)', url: 'https://resumeworded.com', type: 'tool' },
    ],
    whatToIgnore: [
      'Don\'t use fancy resume templates — ATS can\'t parse them',
      'Don\'t list skills you can\'t explain in an interview',
    ],
  },
  {
    id: 'stage-10',
    stageNumber: 10,
    title: 'Company-Specific Preparation',
    description: 'Tailor your prep for specific companies — know what each company tests.',
    difficulty: 'Advanced',
    estimatedWeeks: 3,
    icon: '🏢',
    color: '#2dd4bf',
    topics: [
      { id: 't10-1', title: 'Service Companies: TCS, Infosys, Wipro, Accenture', type: 'company', duration: '3 days' },
      { id: 't10-2', title: 'Mid-Tier: Capgemini, Cognizant, HCL', type: 'company', duration: '2 days' },
      { id: 't10-3', title: 'Product: Flipkart, Paytm, Swiggy', type: 'company', duration: '4 days' },
      { id: 't10-4', title: 'FAANG: Amazon, Microsoft, Google', type: 'company', duration: '1 week' },
      { id: 't10-5', title: 'Startups Preparation', type: 'company', duration: '3 days' },
    ],
    tasks: [
      'List the exact round pattern for each target company',
      'Solve the past 3 years of OA questions for each company',
      'Research company culture and recent projects before each interview',
    ],
    resources: [
      { title: 'GeeksForGeeks Company Prep', url: 'https://www.geeksforgeeks.org/company-preparation', type: 'website' },
      { title: 'Glassdoor Interview Experiences', url: 'https://www.glassdoor.com', type: 'website' },
    ],
    whatToIgnore: [
      'Don\'t apply to companies you haven\'t researched',
    ],
  },
  {
    id: 'stage-11',
    stageNumber: 11,
    title: 'Placement Execution',
    description: 'Apply smartly, track applications, and execute your placement campaign.',
    difficulty: 'Intermediate',
    estimatedWeeks: 8,
    icon: '⚡',
    color: '#f97316',
    topics: [
      { id: 't11-1', title: 'Job Application Strategy', type: 'execution', duration: '1 day' },
      { id: 't11-2', title: 'Track Applications (Spreadsheet)', type: 'execution', duration: 'Ongoing' },
      { id: 't11-3', title: 'OA (Online Assessment) Strategy', type: 'execution', duration: 'Ongoing' },
      { id: 't11-4', title: 'Managing Multiple Interview Pipelines', type: 'execution', duration: 'Ongoing' },
      { id: 't11-5', title: 'Post-Rejection Recovery', type: 'execution', duration: '1 day' },
      { id: 't11-6', title: 'Offer Negotiation Basics', type: 'execution', duration: '1 day' },
    ],
    tasks: [
      'Apply to minimum 3 companies every week',
      'Log every application in a tracker (Company, Date, Status)',
      'Set follow-up reminders 1 week after applying',
    ],
    resources: [
      { title: 'LinkedIn Jobs', url: 'https://www.linkedin.com/jobs', type: 'tool' },
      { title: 'Instahyre', url: 'https://www.instahyre.com', type: 'tool' },
    ],
    whatToIgnore: [
      'Don\'t apply to 50 companies with no tracking — quality over quantity',
      'Don\'t give up after first rejection — the average is 15-20 rejections before an offer',
    ],
  },
  {
    id: 'stage-12',
    stageNumber: 12,
    title: 'Industry-Level Skills',
    description: 'Stand out from the crowd with production-grade engineering knowledge.',
    difficulty: 'Advanced',
    estimatedWeeks: 4,
    icon: '🏭',
    color: '#818cf8',
    topics: [
      { id: 't12-1', title: 'Docker & Containerization', type: 'industry', duration: '3 days' },
      { id: 't12-2', title: 'Kubernetes Basics', type: 'industry', duration: '3 days' },
      { id: 't12-3', title: 'CI/CD Pipelines (GitHub Actions)', type: 'industry', duration: '3 days' },
      { id: 't12-4', title: 'AWS Basics (EC2, S3, Lambda)', type: 'industry', duration: '1 week' },
      { id: 't12-5', title: 'Redis & Caching', type: 'industry', duration: '2 days' },
      { id: 't12-6', title: 'Kafka Basics', type: 'industry', duration: '2 days' },
      { id: 't12-7', title: 'Microservices Architecture', type: 'industry', duration: '4 days' },
      { id: 't12-8', title: 'Logging & Monitoring', type: 'industry', duration: '2 days' },
      { id: 't12-9', title: 'Clean Code & Testing', type: 'industry', duration: '3 days' },
    ],
    tasks: [
      'Deploy a dockerized app to AWS EC2',
      'Set up a GitHub Actions CI/CD pipeline',
      'Implement Redis caching in your existing project',
    ],
    resources: [
      { title: 'AWS Free Tier', url: 'https://aws.amazon.com/free', type: 'tool' },
      { title: 'TechWorld with Nana (Docker/K8s)', url: 'https://www.youtube.com/@TechWorldwithNana', type: 'video' },
    ],
    whatToIgnore: [
      'Don\'t learn all cloud providers at once — master AWS first',
      'Don\'t skip until you have at least 1 deployed project',
    ],
  },
];

export default stages;
